# Generated by Django 3.1.7 on 2021-04-08 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phone_auth', '0004_auto_20210404_1959'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailaddress',
            name='is_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='phonenumber',
            name='is_verified',
            field=models.BooleanField(default=False),
        ),
    ]
